Repository 0chain/gosdk, pull requests merged in 2024-09, with the labels that each got.

#1593 Fix: return transaction nonce if certain status code received
  zboxcore/sdk/sdk.go
  zboxcore/sdk/transaction.go
Labels: bug

#1460 Zauth support (wasm/clis)
  core/conf/config.go
  core/conf/config_test.go
  core/sys/vars.go
  core/transaction/entity.go
  core/version/version.go
  core/zcncrypto/bls0chain_herumi_test.go
  core/zcncrypto/signature_scheme.go
  mobilesdk/zboxapi/client.go
  mobilesdk/zcn/smartcontract.go
  wasmsdk/allocation.go
  wasmsdk/auth_txn.go
  wasmsdk/blobber.go
  wasmsdk/cache.go
  wasmsdk/jsbridge/func.go
  wasmsdk/jsbridge/input.go
  wasmsdk/jsbridge/webworker.go
  wasmsdk/jsbridge/zcnworker.js.tpl
  wasmsdk/proxy.go
  wasmsdk/sdk.go
  wasmsdk/smartcontract.go
  wasmsdk/wallet.go
  wasmsdk/zbox.go
  winsdk/zboxapi.go
  zboxapi/sdk.go
  zboxapi/sdk_test.go
  zboxcore/client/entity.go
  zboxcore/marker/writemarker.go
  zboxcore/sdk/allocation.go
  zboxcore/sdk/chunked_upload_blobber.go
  zboxcore/sdk/chunked_upload_process_js.go
  zboxcore/sdk/commitworker.go
  zboxcore/sdk/common.go
  zboxcore/sdk/copyworker.go
  zboxcore/sdk/copyworker_test.go
  zboxcore/sdk/deleteworker.go
  zboxcore/sdk/dirworker.go
  zboxcore/sdk/downloadworker.go
  zboxcore/sdk/filemetaworker.go
  zboxcore/sdk/filerefsworker.go
  zboxcore/sdk/filestatsworker.go
  zboxcore/sdk/listworker.go
  zboxcore/sdk/moveworker.go
  zboxcore/sdk/multi_operation_worker.go
  zboxcore/sdk/renameworker.go
  zboxcore/sdk/rollback.go
  zboxcore/sdk/sdk.go
  zboxcore/sdk/sharerequest.go
  zboxcore/sdk/transaction.go
  zboxcore/sdk/writemarker_mutex.go
  zboxcore/zboxutil/http.go
  zboxcore/zboxutil/util.go
  zcncore/transaction.go
  zcncore/transaction_base.go
  zcncore/transaction_mobile.go
  zcncore/transactionauth.go
  zcncore/transactionauth_base.go
  zcncore/transactionauth_mobile.go
  zcncore/wallet_base.go
  zcncore/zauth.go
Labels: WIP

#1594 Fix: wallet information initialization
  zcncore/wallet_base.go
Labels: bug

#1614 Fix: demo page initialization
  wasmsdk/demo/index.html
  wasmsdk/demo/zcn.js
Labels: bug

#1625 Feature: modify JWT logic
  mobilesdk/zboxapi/client.go
  wasmsdk/demo/index.html
  wasmsdk/demo/zcn.js
  wasmsdk/proxy.go
  wasmsdk/zbox.go
  winsdk/zboxapi.go
  zboxapi/sdk.go
  zboxapi/sdk_test.go
Labels: enhancement

#1626 Fix: move transaction scheme to mobile package
  core/transaction/entity.go
  core/transaction/transaction.go
  core/transaction/transaction_mobile.go
  mobilesdk/zcn/smartcontract.go
  zboxcore/sdk/transaction_mobile.go
  zcncore/transaction.go
  zcncore/transaction_base.go
  zcncore/transaction_mobile.go
  zcncore/transactionauth.go
  zcncore/transactionauth_base.go
  zcncore/transactionauth_mobile.go
Labels: enhancement
